### ISSUE TITLE
Wrong file count with APE files

### ISSUE THREAD

**Issue by glu8716** [vc-01/metadata-osd#10]
![2023-03-10_21-09](https://user-images.githubusercontent.com/33501455/224418360-7483c594-0a1c-4f6f-9ced-c0d4f236eb30.png)
I have an album with 4 tracks in APE format, however the osd only shows 1/1 instead of 1/4 tracks as you can see from the image. The album is tagged correctly.

**Comment by vc-01** [comment]
The line "1/1" really reads the currently selected file is 1 (first) out of 1 in playlist. You can verify the currently queued playlist by pressing _F8_ (default key) in mpv. If there's only one file listed, your playlist consists of one file and everything is correct - besides perhaps the insufficient documentation on what is being shown by the metadata script.

If you want to have the album's track number - if filled up in metadata - showed along with the playlist position / playlist size, you can add `show_albumtracknumber=yes` to your configuration file.

There will be some additional text minimization coming with it which is documented - means it's a feature :)

See [README.md](https://github.com/vc-01/metadata-osd#chapter-number-and-track-number) for details but any feedback is appreciated.

**Comment by glu8716** [comment]
Oh, you are right, by pressing the F8 key I can see that mpv isn't generating playlists for APE files. Since I can see the correct number of files if I open other formats like FLAC or mp3 (both with your script and with the F8 key), I assume there is something wrong with mpv and the APE format. I should report the bug to them then, sorry if I came here, but I noticed this because of your script!

By the way since you mentioned the `show_albumtracknumber` option I tried it, as I hadn't yet. Nothing changed for me, here's a picture for reference:
![2023-03-11_12-23](https://user-images.githubusercontent.com/33501455/224481563-3e0bba4d-2619-4518-b508-1fcce92f57d1.png)

EDIT: Okay, turned out that the playlists I was seeing were the ones created by the `autoload` mpv's script, which I forgot I have. And since it wasn't configured with APE files, while it was for other formats, I wasn't seeing the file count with your script. 
The fact that the `show_albumtracknumber` option isn't working seems to be related to the `autoload` script too, as if I delete the script the `show_albumtracknumber` option works.

**Comment by vc-01** [comment]
The first part is clear. For the second --> this is (most probably) an aforementioned "feature": if current playlist position equals to the current album's track number, only the playlist position is showed, hence avoiding duplicate information on OSD as e.g.:
_Track: 3
[3/14]_

Since the 'autoload' plugin is loading always _all_ tracks / files in the folder, the text minimization is also being _always_ applied. If you load a whole folder with mpv without the 'autoload' plugin the minimization will still apply.

This will not be directly linked to the 'autoload' plugin, only as a sort of side effect.

**Comment by glu8716** [comment]
I see! Thanks for the explanation, everything is clearer now. Thanks again for the awesome script!

**Comment by vc-01** [comment]
Thank you too. I realize now the documentation is missing on things, it will get improvements over time piece by piece.
