### ISSUE TITLE
[Feature Request]: Add option where script will only activate if it is only playing audio

### ISSUE THREAD

**Issue by NaiveInvestigator** [vc-01/metadata-osd#2]
It would be a neat addition imo, I find it distracting while watching vids.

Edit: Love your script btw! Really nice!.

**Comment by vc-01** [comment]
I find this request reasonable to implement - as a general feature this might be a "nice-to-have" one.

This could be implemented either by leveraging mpv's conditional profiles ([_Conditional auto profiles_](https://mpv.io/manual/master/#conditional-auto-profiles)) together with _script-opts_ option to switch off the script. This approach would bring full control over when to enable / disable the script with a disadvantage of slightly more complicated setup. This would go into the main _mpv.conf_ file and look something similar to the following:
```
[metadata-osd-isvideo]
profile-cond=<profile_cond_isvideo>
profile-restore=copy
script-opts=metadata-osd-enable_on_start=no
```
Second option would be to implement it directly into the script, restricting to only basic track selection (to make it simple) with a help of a new variable, as for example:
```enable_for_tracks=video,audio,audio_with_albumart,picture```

I need to ask first though; what is the "distracting" part namely? The initial OSD showing the movie title or the OSD showing chapter titles during playback? (Many times, I saw chapter titles broken, filled with garbage like timestamps etc., that's true.)
The main OSD should automatically hide for movies after 5 seconds (by default) or as defined by the _autohide_timeout_sec_ option. It should not be getting on one's nerves too much if it works as it should.

I was thinking about it, to have an option to disable the chapter OSD could perhaps be the fix (?).

**Comment by NaiveInvestigator** [comment]
I have tried changing it with from `mpv.conf` but it doesn't work for some reason. It can only be changed globally and not be changed with a profile, not so sure why.

>The initial OSD showing the movie title or the OSD showing chapter titles during playback? 

Both for me sadly,  I think I forgot this important fact tho that I use [uosc](https://github.com/darsain/uosc) along with this script and it works! but it might also be the cause that the timestamps pop up and fade out a lot. This annoys me usually when i watch YouTube vids where there is a lot of timestamps and anime which have timestamps included too.

![image](https://user-images.githubusercontent.com/72654596/184652476-b2f954e8-f6db-4d83-9249-5b86b7f8c876.png)

**Comment by vc-01** [comment]
>  It can only be changed globally and not be changed with a profile, not so sure why.

Yes, I tested it too and it's not working. This was a misunderstanding. I was _just_ thinking out loud how this could be implemented. The script would need to take the _script-opts_ option into consideration somehow, I think. But I haven't looked into why this is not working yet.

> I think I forgot this important fact tho that I use [uosc](https://github.com/darsain/uosc) along with this script and it works! but it might also be the cause that the timestamps pop up and fade out a lot.

The script is observing chapter title changes and also current video track, but the latter is not firing the OSD. I will check with the 'uosc' script if something unplanned is happening with event handlers. The main OSD should pop up only on file load event.

Anyway, this brings the following TODO list:
- [x] Make script's options reachable via _script-opts_ mpv option
- [x] Add option to disable chapter title OSD (OSD-2)
- [x] Selectively enable for audio/video/picture tracks
- [x] (low prio) Check with 'uosc' script if event handlers are working properly

And now, thank you for your feedback! This will surely make the script better. Until then though, your only option is the main kill switch (_F1_ key if not rebound from default) for the broken videos.

**Comment by vc-01** [comment]
On topic: _Make script's options reachable via script-opts mpv option_

This, after all works. I had another 'script-opts' defined in 'mpv.conf' _after_ script-opts for metadata-osd script which reset the previous option list. This same behavior is observable from command line.

A functional disabler is: `script-opts=metadata-osd-enable_on_start=no`

Thinking out loud: Now I see that underscores, instead of minuses blend in nicer for script names. Maybe will rename.

**Comment by vc-01** [comment]
This approach with 'script-opts' works _rarely_ (once in a time) with conditional auto profiles, it does _always_ work if the same profile is selected manually with '--profile=\<profilename\>'. This is obscure. 
I tested with profile:
```
[test]
profile-cond=true
script-opts=metadata-osd-enable_on_start=no
````

**Comment by NaiveInvestigator** [comment]
I have found according to this [comment](https://github.com/mpv-player/mpv/issues/10181#issuecomment-1125163399) that :

>Yeah, currently `--load-scripts`, `--scripts` and similar options do not work at runtime so a profile condition like this is not possible.

Which entirely explains why script-opts works when applied without a profile but not inside one, since profiles work on runtime.

If that is the case, it seems that using the `mpv.conf` method may not work.

So we may have to add it on the script itself. I'm not sure if it is the best method, but one way of that i was thinking of was to make a function which runs before anything else and decides whether `enable_on_start` should be true or not, depending if the file is a picture,audio or video.

**Comment by vc-01** [comment]
Thank you for a good find! Now, the first approach will have to be left behind.

> So we may have to add it on the script itself ...

I don't really see a problem implementing it, my idea was in any case to explore all options available. (Looks they weren't really.)

**Comment by vc-01** [comment]
I couldn't reproduce any issues while both 'uosc' and 'metadata-osd' scripts were running alongside. I tried the default configuration for 'uosc' with no menu (only).

I will close this issue in some couple of days if no apparent bugs pop up with the latest changes.

**Comment by NaiveInvestigator** [comment]
I tried the new update! But sadly it still doesn't work for me. 

This is my script-opts that i used:
```
#
# Example configuration file for 'metadata_osd.lua' script
# with preset defaults.
#

#enable_on_start=no
#enable_for_audio=yes
#enable_for_audio_withalbumart=yes
#enable_for_video=no
#enable_for_image=no
#enable_osd_2=no
#autohide_for_audio=no
#autohide_for_audio_withalbumart=no
#autohide_for_video=yes
#autohide_for_image=yes
#key_toggleenable=F1
#key_toggleautohide=F5
#key_toggleosd_1=''
#key_toggleosd_2=''
#key_reset_usertoggled=F6
#key_showstatusosd=''
#autohide_timeout_sec=5
#autohide_statusosd_timeout_sec=10
#osd_message_maxlength=96

```

But even with the default config (no scripts, configs and shaders whatsoever), whenever I try to play a video the script is still activated when played. Unless i am misunderstanding what `enable_for_video` does welp.

![image](https://user-images.githubusercontent.com/72654596/185888529-41ba19fb-db07-431a-b887-fc194107f30d.png)

**Comment by vc-01** [comment]
Uncomment the options in question:
```
enable_for_video=no
enable_for_image=no
```

**Comment by NaiveInvestigator** [comment]
> Uncomment the options in question:
> 
> ```
> enable_for_video=no
> enable_for_image=no
> ```

OMG no lmao sorry sorry I was tired didn't see that at all . Sorry for bothering you sincerely. :< Will report after I test it properly this time lol.

**Comment by vc-01** [comment]
No problem. Your feedback so far was very valuable.

**Comment by NaiveInvestigator** [comment]
Thank you so much for your consideration! After testing it for the whole day, I came across with no problems as of yet also, so I think it is safe close this issue too! Will report in if there is any issues down the line!

This script is now perfect!! <3

be proud loll

Thanks again for making this! I really really appreciate for you listening to my thoughts too!! I hope you have a pleasant day/night.

**Comment by vc-01** [comment]
Please step by anytime! Your feedback was much appreciated. Also, thank you a lot for testing, companies pay for it. :)

Then going off topic to the other moving parts of the script, I can hardly believe the metadata selection will always work properly for all possible cases and media collections. It works for mine, obviously, but ... I expect issues. :)

And if someone reports one, I would need a dedicated function in the script, the user will be asked to run the script with debugging enabled and then sending back the output with all possible metadata and their friends mpv can get and based on that I could possibly do something about it - just thinking here, as preparation.

**Comment by NaiveInvestigator** [comment]
> Then going off topic to the other moving parts of the script, I can hardly believe the metadata selection will always work properly for all possible cases and media collections. It works for mine, obviously, but ... I expect issues. :)

Only time will tell ig. Tho I pray it doesn't break lol (less work and all :>). But imho it seems pretty solid tho. I did try on it like a mixture on formats i had on hand like : mp3, ogg, m4a, jpg, mkv, png and also on webm (with and without video) and it works very well. And also ones that had cover arts on them too. I was actually surprised with the webm one. I expected to that in both cases that the script wouldn't activate but on the no video webm one, the script again activated. Just blew my socks off lol.
 
> And if someone reports one, I would need a dedicated function in the script, the user will be asked to run the script with debugging enabled and then sending back the output with all possible metadata and their friends mpv can get and based on that I could possibly do something about it - just thinking here, as preparation.

Yep seems like a good idea to me! I bet it will make things easier.

Edit: Added my config file here so you get what i am rambling about lol on the first paragraph.

```
#
# Example configuration file for 'metadata_osd.lua' script
# with preset defaults.
#

#enable_on_start=yes
enable_for_audio=yes
enable_for_audio_withalbumart=yes
enable_for_video=no
enable_for_image=no
#enable_osd_2=yes
#autohide_for_audio=no
#autohide_for_audio_withalbumart=no
#autohide_for_video=yes
#autohide_for_image=yes
#key_toggleenable=F1
#key_toggleautohide=F5
#key_toggleosd_1=''
#key_toggleosd_2=''
#key_reset_usertoggled=F6
#key_showstatusosd=''
#autohide_timeout_sec=5
#autohide_statusosd_timeout_sec=10
#osd_message_maxlength=96

```

**Comment by vc-01** [comment]
The album cover behind-logic is provided nicely by mpv, the credits are due there.

But in any case, you tested the script and came back with results which is a contribution. I can mention your efforts, if you're okay with it.

**Comment by NaiveInvestigator** [comment]
Nah tis ok lol. No need to do it. I'm fine if you want to mention them tho.

**Comment by vc-01** [comment]
> if you want to ...

I don't want to, but you can let me know when you decide.

EDIT: I believe I need to ask first. I haven't checked what's the right way to do it.
