### ISSUE TITLE
help : some INFO && [feature-request] : mpv-lrc

### ISSUE THREAD

**Issue by OmiChrome** [vc-01/metadata-osd#4]
i just want to know ur configs  like 
- which `font` ur using , and what is used in readme.md  - [picture](https://github.com/vc-01/metadata-osd/blob/main/screenshot.png)
- ur personal config? idk 😅
- also i need some font `suggestion ` mine looks crap 

**THE MAIN thing**
[mpv-lrc](https://sr.ht/~guidocella/mpv-lrc/) = is a script to get lyrics for current-song  (it does work but, 😞 )

- it can't work with **online streams** 
- can't work with path $filenames
- can't get subtitles- lyric for video's (non-music ) <-- i dont think its needed
- bit outdated 

 **so what i want ?**
i want U(VC-01)  chad  to look into mpv-lrc to make it awesome more 😄 
i am not dev (bearly no html) 

but i wan't lyrics in music ( ﾉ ﾟｰﾟ)ﾉ

here is some - image of issue's loll
![image](https://user-images.githubusercontent.com/108952834/194935570-036f816a-f5f0-4beb-a9d7-1cd9c31c1d67.png)
![image](https://user-images.githubusercontent.com/108952834/194935612-027db023-7e1f-48ac-bdf8-26536868c390.png)

_these images are from online- youtube-stream through mpv  _
 
why i asked u coz u  are good at dealing with Metadata 

at the end 
 🙏  thx for the metadata - osd

**Comment by vc-01** [comment]
> which font ur using...

I can answer that if you tell me how I can find out.

I can tell it's the default what you get on latest Arch Linux with theirs pre-compiled mpv package (nothing related to fonts in my 'mpv.conf'). Same goes for the screenshot.

To the other part; I'm willing to fix and work on anything related to my script but I'm not getting your question exactly, is the attached screenshot from 'metadata-osd' script?

If you need support for 'mpv-lrc', this is a wrong place to ask for.

**Comment by vc-01** [comment]
Closing: _No response_.

Step by anytime, but you won't get support for different projects here (obviously).
