### ISSUE TITLE
Album's release date font doesn't respect scaling

### ISSUE THREAD

**Issue by glu8716** [vc-01/metadata-osd#7]
I wanted to make the text smaller and this is how I edited the script:
```
style_fsc_osd_1_textarea_1 = 60,
style_fsc_osd_1_textarea_2 = 60,
style_fsc_osd_1_textarea_3 = 60,
style_fsc_osd_1_textarea_4 = 60,
style_fsc_osd_2_textarea_1 = 100,
```
The release date however doesn't respect the value I set.
![2023-02-20_20-56](https://user-images.githubusercontent.com/33501455/220189128-bfaecca0-9547-40fe-a689-ab06d36c5586.png)

**Comment by vc-01** [comment]
Thank you for the bug report, I will look at this soon.

**Comment by vc-01** [comment]
The reported bug has been fixed with the latest commit. I would also suggest using a separate configuration file so updating the script would be as easy as downloading & placing it in the right place. Config file has a slightly different syntax so the options would read:
```
style_fsc_osd_1_textarea_1=60
style_fsc_osd_1_textarea_2=60
style_fsc_osd_1_textarea_3=60
style_fsc_osd_1_textarea_4=60
style_fsc_osd_2_textarea_1=100
```

Please refer to [README.md](https://github.com/vc-01/metadata-osd#installation--configuration) for the config file setup & in case, let me know if something is missing there or could be improved.

**Comment by glu8716** [comment]
I've actually missed the part about the external configuration, thanks for the tip. I can confirm it works now, thanks!
I tried to make more edits by using it and I think I found another bug. Setting `style_fontstyle_osd_1_textarea_2_releasedate` to `italic` or `bold` doesn't work, while it does if editing the lua script.

EDIT: nevermind, my bad, sorry. Those settings don't need to be inside the quotation marks.

**Comment by vc-01** [comment]
No, you were right that this is another bug. First, user settings **mustn't** be in quotation marks unless the quotation marks are themselves part of the value plus **they're** in the example configuration file. I will fix the example config file as well and will thank you with contributing once more :)

Here is the link to mpv documentation on user options:
[mp.options functions ](https://github.com/mpv-player/mpv/blob/86093fcae7881f1a2be2e481af8d6a566733a99a/DOCS/man/lua.rst#mpoptions-functions)

**Comment by glu8716** [comment]
I'm glad I helped :)

**Comment by vc-01** [comment]
Sure. Well, this seems done.
