### ISSUE TITLE
Adding "Title: ", "Album: "... text before the actual metadata

### ISSUE THREAD

**Issue by glu8716** [vc-01/metadata-osd#8]
I'd like to have a text before the metadata that indicates what is shown on the side. For example:
Artist: _actual artist name_
Album: _actual album name_
Title: _actual song name_

Is this possible?

**Comment by vc-01** [comment]
I was thinking about making the OSD templates visible as another user setting already longer time ago. With that, the layout would become changeable, e.g. either of the text areas would be movable up or down, text prefixes could be added as you're asking for etc. This especially applies to another group of sub options for displaying track numbers prefixed with "Track: " or chapter numbers prefixed with "Chapter: " on which I myself don't have clear vision which is the best visual for it. Sometimes I like it, sometimes I don't (I'm speaking about options 'show_albumtracknumber' and 'show_chapternumber').

I will keep this open and most probably implement it.

Only to mention, this script is made for multiple media types not only audio files but also movies or live streaming media etc., whatever mpv supports. Static texts as "Artist" or "Album" in the template would give bad information for a movie file (that's also why I'm using more general -and harder-to-grab- names like "text area" for the fields then "album" / "artist").

To add to that, the script is trying to get _something_ usable for the field, it can be a folder name if nothing else is available for example. Folder name will not always be "artist" but it has proved to be useful so far - it's still better than showing nothing. 

There could be multiple templates for each media type but I wouldn't want to go that way yet.

**Comment by glu8716** [comment]
Thanks for the clear explanation. Unfortunately I'm just a normal user and don't really know how code works, so I apologize in advance if making something like this would be troublesome.

I don't think having these information is necessary with video and image files. I mean, having these prefixes is something that is needed with music, but not really with other media. For example this would be particularly useful when you can't read a language and you want to quickly identify which field is the album or which one is the song, without having to remember the layout position. But you wouldn't have this problem with a video files which only has a title. This is something that should be music related.

As for the folder name thing, there could be another dedicated text when the script doesn't find a particular tag in the file.

**Comment by vc-01** [comment]
Any user feedback so far has showed very valuable. Now, I have bigger motivation to actually do it than only think about doing it. :) I was elaborating loud the planned approach which helps me and explains as well. Your last response has added to it too because there will be a need for another template for folder name / file name fallback (it seems). You don't need to think about implementation details and anyway, this has been half done already. I was approaching it anyway.

The plan is then to have static templates for different media types which the user fills in to his/her needs. Dynamic fill is not planned. There has nowhere been stated yet which text area carries what data, I will keep it that way, so it can stay open to changes. Working with metadata is best effort, e.g. fields are not always filled as one would expect. Having strong point on what is where would only bring bug reports.

When the time allows, I will post an update on this.

**Comment by vc-01** [comment]
With the latest commit it is now possible to achieve what has been asked for by adding the following to the configuration file:

```
content_osd_1_textarea_1_audio=##TEXTAREA_1_METAKEY##: ##TEXTAREA_1_GEN##
content_osd_1_textarea_2_audio=##TEXTAREA_2_METAKEY##: ##TEXTAREA_2_GEN##
content_osd_1_textarea_3_audio=##TEXTAREA_3_METAKEY##: ##TEXTAREA_3_GEN##
content_osd_1_textarea_1_audio_withalbumart=##TEXTAREA_1_METAKEY##: ##TEXTAREA_1_GEN##
content_osd_1_textarea_2_audio_withalbumart=##TEXTAREA_2_METAKEY##: ##TEXTAREA_2_GEN##
content_osd_1_textarea_3_audio_withalbumart=##TEXTAREA_3_METAKEY##: ##TEXTAREA_3_GEN##
```

I don't find this particularly useful and so, will keep it kind of hidden and undocumented. If more users come with similar requests, this can receive further updates.

**Comment by glu8716** [comment]
Woah, thanks a lot for the quick response. This is exactly what I wanted and now makes this script a must have for me. Thanks a lot for the hard work :)

**Comment by vc-01** [comment]
The solution is kind of half-baked. It will work with audio files but playing only a little bit more with it would show insufficiencies very quickly. I might work on this a bit more in the future. I'm not saying it is a complete nonsense to have this feature.
